// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using RFactory.Infrastructure.Entities;

namespace RFactory.Infrastructure.Data;

public partial class RFactoryContext : DbContext
{
    public RFactoryContext(DbContextOptions<RFactoryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<Bom> Boms { get; set; }

    public virtual DbSet<BomDetail> BomDetails { get; set; }

    public virtual DbSet<Factory> Factories { get; set; }

    public virtual DbSet<Function> Functions { get; set; }

    public virtual DbSet<FunctionGroup> FunctionGroups { get; set; }

    public virtual DbSet<GoodsIssue> GoodsIssues { get; set; }

    public virtual DbSet<GoodsIssueDetail> GoodsIssueDetails { get; set; }

    public virtual DbSet<GoodsReceipt> GoodsReceipts { get; set; }

    public virtual DbSet<GoodsReceiptDetail> GoodsReceiptDetails { get; set; }

    public virtual DbSet<Holiday> Holidays { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<InventoryCycleCount> InventoryCycleCounts { get; set; }

    public virtual DbSet<InventoryCycleCountDetail> InventoryCycleCountDetails { get; set; }

    public virtual DbSet<InventoryLot> InventoryLots { get; set; }

    public virtual DbSet<InventoryReservation> InventoryReservations { get; set; }

    public virtual DbSet<InventorySerial> InventorySerials { get; set; }

    public virtual DbSet<InventoryTransaction> InventoryTransactions { get; set; }

    public virtual DbSet<Line> Lines { get; set; }

    public virtual DbSet<Machine> Machines { get; set; }

    public virtual DbSet<MachineType> MachineTypes { get; set; }

    public virtual DbSet<MaterialIssue> MaterialIssues { get; set; }

    public virtual DbSet<MaterialIssueDetail> MaterialIssueDetails { get; set; }

    public virtual DbSet<MaterialReturn> MaterialReturns { get; set; }

    public virtual DbSet<MaterialReturnDetail> MaterialReturnDetails { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductType> ProductTypes { get; set; }

    public virtual DbSet<ProductUnit> ProductUnits { get; set; }

    public virtual DbSet<Routing> Routings { get; set; }

    public virtual DbSet<RoutingOperation> RoutingOperations { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<ShiftBreak> ShiftBreaks { get; set; }

    public virtual DbSet<StockTransfer> StockTransfers { get; set; }

    public virtual DbSet<StockTransferDetail> StockTransferDetails { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<TableBase> TableBases { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<UnitCategory> UnitCategories { get; set; }

    public virtual DbSet<UnitConversion> UnitConversions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<UserGroupLink> UserGroupLinks { get; set; }

    public virtual DbSet<UserGroupRightDistribution> UserGroupRightDistributions { get; set; }

    public virtual DbSet<Warehouse> Warehouses { get; set; }

    public virtual DbSet<WarehouseLocation> WarehouseLocations { get; set; }

    public virtual DbSet<WarehouseZone> WarehouseZones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Area>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("area", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.AreaCode).HasMaxLength(50);
            entity.Property(e => e.AreaName).HasMaxLength(255);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Bom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("bom", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.BomCode).HasMaxLength(50);
            entity.Property(e => e.BomName).HasMaxLength(255);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValueSql("'0'");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Version).HasMaxLength(255);
        });

        modelBuilder.Entity<BomDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("bom_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.FixedScrapQty).HasComment("Số lượng hao hụt cố định");
            entity.Property(e => e.ProductId).HasComment("ID nguyên vật liệu hoặc bán thành phẩm");
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.ScrapRate)
                .HasPrecision(8, 4)
                .HasComment("% hao hụt");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Factory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("factory", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.FactoryCode).HasMaxLength(50);
            entity.Property(e => e.FactoryName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Function>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("functions", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.FunctionGroupId, "IX");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.FunctionCode).HasMaxLength(50);
            entity.Property(e => e.FunctionName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<FunctionGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("function_group", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.ParentId, "IX_ParentId");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<GoodsIssue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("goods_issue", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.IssueNo, "IssueNo").IsUnique();

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.ApprovedDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.IssueDate).HasColumnType("datetime");
            entity.Property(e => e.IssueNo).HasMaxLength(50);
            entity.Property(e => e.PostedDate).HasColumnType("datetime");
            entity.Property(e => e.ReferenceType).HasMaxLength(50);
            entity.Property(e => e.Remark).HasColumnType("text");
            entity.Property(e => e.Status).HasComment("1: Purchase; 2: Production; 3: Return; 4: Transfer In; 5: Adjustment");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<GoodsIssueDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("goods_issue_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.LotNo).HasMaxLength(100);
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.Remark).HasColumnType("text");
            entity.Property(e => e.SerialNo).HasMaxLength(100);
            entity.Property(e => e.UnitPrice).HasPrecision(18, 6);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<GoodsReceipt>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("goods_receipt", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.ReceiptNo, "ReceiptNo").IsUnique();

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.ApprovedDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.PostedDate).HasColumnType("datetime");
            entity.Property(e => e.ReceiptDate).HasColumnType("datetime");
            entity.Property(e => e.ReceiptNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ReceiptType).HasComment("1: Purchase; 2: Production; 3: Return; 4: Transfer In; 5: Adjustment");
            entity.Property(e => e.ReferenceType).HasMaxLength(50);
            entity.Property(e => e.Remark).HasColumnType("text");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<GoodsReceiptDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("goods_receipt_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpireDate).HasColumnType("datetime");
            entity.Property(e => e.LotNo).HasMaxLength(100);
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.ReceivedQty).HasPrecision(18, 6);
            entity.Property(e => e.Remark).HasColumnType("text");
            entity.Property(e => e.SerialNo).HasMaxLength(100);
            entity.Property(e => e.UnitPrice).HasPrecision(18, 6);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Holiday>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("holiday", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.HolidayCode).HasMaxLength(50);
            entity.Property(e => e.HolidayName).HasMaxLength(255);
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("inventory", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.AvailableQuantity).HasPrecision(18, 6);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.LastTransactionDate).HasColumnType("datetime");
            entity.Property(e => e.LotNo).HasMaxLength(255);
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.ReservedQuantity).HasPrecision(18, 6);
            entity.Property(e => e.SerialNo).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<InventoryCycleCount>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("inventory_cycle_count", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CountDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasComment("Người kiểm kê");
        });

        modelBuilder.Entity<InventoryCycleCountDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("inventory_cycle_count_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.ActualQuantity).HasPrecision(18, 6);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DifferenceQuantity).HasPrecision(18, 6);
            entity.Property(e => e.LotNo).HasMaxLength(255);
            entity.Property(e => e.SystemQuantity).HasPrecision(18, 6);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<InventoryLot>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("inventory_lot", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiredDate).HasColumnType("datetime");
            entity.Property(e => e.LotNo).HasMaxLength(255);
            entity.Property(e => e.ManufactureDate).HasColumnType("datetime");
            entity.Property(e => e.SupplierLotNo).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<InventoryReservation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("inventory_reservation", tb => tb.HasComment("Giữ hàng cho Work Order hoặc Sales Order."))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.ReferenceType).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<InventorySerial>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("inventory_serial", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.SerialNo).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<InventoryTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("inventory_transaction", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.ReferenceType).HasComment("1: GR; 2: GI; 3: TRANSFER_IN; 4: TRANSFER_OUT; 5: MATERIAL_ISSUE; 6: MATERIAL_RETURN; 7: PRODUCTION_RECEIPT; 8: PRODUCTION_CONSUME; 9: ADJUSTMENT; 10: SCRAP\\n");
            entity.Property(e => e.TransactionDate).HasColumnType("datetime");
            entity.Property(e => e.TransactionNo).HasMaxLength(255);
            entity.Property(e => e.TransactionType).HasComment("1: RECEIPT; 2: ISSUE; 3: TRANSFER; 4: ADJUST; 5: PRODUCTION_IN; 6: PRODUCTION_OUT; 7: SCRAP");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Line>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("line", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.LayoutImage).HasMaxLength(550);
            entity.Property(e => e.LineCode).HasMaxLength(50);
            entity.Property(e => e.LineName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Machine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("machine", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.MachineCode).HasMaxLength(50);
            entity.Property(e => e.MachineName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<MachineType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("machine_type", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.MachineTypeCode).HasMaxLength(50);
            entity.Property(e => e.MachineTypeName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<MaterialIssue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("material_issue", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.IssueDate).HasColumnType("datetime");
            entity.Property(e => e.IssueNo).HasMaxLength(50);
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'1'")
                .HasComment("1: Draft; 2: Approved; 3: Posted; 4: Cancelled");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<MaterialIssueDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("material_issue_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.LotNo).HasMaxLength(100);
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<MaterialReturn>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("material_return", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.ReturnDate).HasColumnType("datetime");
            entity.Property(e => e.ReturnNo).HasMaxLength(50);
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'1'")
                .HasComment("1: Draft; 2: Approved; 3: Posted; 4: Cancelled");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<MaterialReturnDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("material_return_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.LotNo).HasMaxLength(100);
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("menu", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.ParentId, "IX_ParentId");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Icon).HasColumnType("text");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Url).HasMaxLength(255);
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("organization", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.ParentId, "IX_ParentId");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.OrganizationCode).HasMaxLength(50);
            entity.Property(e => e.OrganizationName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("product", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DrawingNo).HasMaxLength(255);
            entity.Property(e => e.DrawingPath).HasMaxLength(255);
            entity.Property(e => e.ProductCode).HasMaxLength(50);
            entity.Property(e => e.ProductName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("product_type", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.ProductTypeCode).HasMaxLength(50);
            entity.Property(e => e.ProductTypeName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductUnit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("product_unit", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.ConversionFactor).HasPrecision(24, 10);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Routing>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("routing", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => new { e.ProductId, e.Version }, "UK_Version").IsUnique();

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<RoutingOperation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("routing_operation", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.RoutingOperationCode).HasMaxLength(50);
            entity.Property(e => e.RoutingOperationName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("shift", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.CrossDay)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.EndTime).HasColumnType("time");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.ShiftCode).HasMaxLength(50);
            entity.Property(e => e.ShiftName).HasMaxLength(255);
            entity.Property(e => e.StartTime).HasColumnType("time");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WorkingMinute).HasPrecision(10, 2);
        });

        modelBuilder.Entity<ShiftBreak>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("shift_break", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.BreakName).HasMaxLength(255);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime).HasColumnType("time");
            entity.Property(e => e.StartTime).HasColumnType("time");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<StockTransfer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("stock_transfer", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.TransferNo, "TransferNo").IsUnique();

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.PostedDate).HasColumnType("datetime");
            entity.Property(e => e.Remark).HasColumnType("text");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'1'")
                .HasComment("1: Draft; 2: Approved; 3: Posted; 4: Cancelled");
            entity.Property(e => e.TransferDate).HasColumnType("datetime");
            entity.Property(e => e.TransferNo).HasMaxLength(50);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<StockTransferDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("stock_transfer_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.LotNo).HasMaxLength(100);
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.SerialNo).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("supplier", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.ContactPerson).HasMaxLength(255);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrencyCode).HasMaxLength(10);
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.PaymentTerm).HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.ShortName).HasMaxLength(100);
            entity.Property(e => e.Status).HasDefaultValueSql("'1'");
            entity.Property(e => e.SupplierCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SupplierType).HasMaxLength(30);
            entity.Property(e => e.TaxCode).HasMaxLength(50);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Website).HasMaxLength(255);
        });

        modelBuilder.Entity<TableBase>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("table_base", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("unit", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DecimalPlaces).HasDefaultValueSql("'2'");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.IsBaseUnit)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.Symbol).HasMaxLength(255);
            entity.Property(e => e.UnitCode).HasMaxLength(50);
            entity.Property(e => e.UnitName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UnitCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("unit_category", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.UnitCategoryCode).HasMaxLength(50);
            entity.Property(e => e.UnitCategoryName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UnitConversion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("unit_conversion", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DivideValue).HasPrecision(24, 10);
            entity.Property(e => e.FormulaType)
                .HasDefaultValueSql("'1'")
                .HasComment("1: MULTIPLY 2: DIVIDE");
            entity.Property(e => e.IsActive).HasDefaultValueSql("'1'");
            entity.Property(e => e.MultiplyValue).HasPrecision(24, 10);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("users", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(550);
            entity.Property(e => e.FullName).HasMaxLength(550);
            entity.Property(e => e.IsAdmin)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.LoginName).HasMaxLength(255);
            entity.Property(e => e.PasswordHash).HasColumnType("text");
            entity.Property(e => e.RefreshToken).HasMaxLength(255);
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_group", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGroupLink>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_group_link", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGroupRightDistribution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_group_right_distribution", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Warehouse>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("warehouse", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WarehouseCode).HasMaxLength(50);
            entity.Property(e => e.WarehouseName).HasMaxLength(255);
        });

        modelBuilder.Entity<WarehouseLocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("warehouse_location", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.MaxCapacity).HasPrecision(18, 6);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WarehouseLocationCode).HasMaxLength(50);
            entity.Property(e => e.WarehouseLocationName).HasMaxLength(255);
        });

        modelBuilder.Entity<WarehouseZone>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("warehouse_zone", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WarehouseZoneCode).HasMaxLength(50);
            entity.Property(e => e.WarehouseZoneName).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}