// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using RFactory.Infrastructure.Entities;

namespace RFactory.Infrastructure.Data;

public partial class RFactoryContext : DbContext
{
    public RFactoryContext(DbContextOptions<RFactoryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<Bom> Boms { get; set; }

    public virtual DbSet<BomDetail> BomDetails { get; set; }

    public virtual DbSet<Factory> Factories { get; set; }

    public virtual DbSet<Function> Functions { get; set; }

    public virtual DbSet<FunctionGroup> FunctionGroups { get; set; }

    public virtual DbSet<Holiday> Holidays { get; set; }

    public virtual DbSet<Line> Lines { get; set; }

    public virtual DbSet<Machine> Machines { get; set; }

    public virtual DbSet<MachineType> MachineTypes { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductType> ProductTypes { get; set; }

    public virtual DbSet<ProductUnit> ProductUnits { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<ShiftBreak> ShiftBreaks { get; set; }

    public virtual DbSet<TableBase> TableBases { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<UnitCategory> UnitCategories { get; set; }

    public virtual DbSet<UnitConversion> UnitConversions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<UserGroupLink> UserGroupLinks { get; set; }

    public virtual DbSet<UserGroupRightDistribution> UserGroupRightDistributions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Area>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("area", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.AreaCode).HasMaxLength(50);
            entity.Property(e => e.AreaName).HasMaxLength(255);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Bom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("bom", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.BomCode).HasMaxLength(50);
            entity.Property(e => e.BomName).HasMaxLength(255);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValueSql("'0'");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Version).HasMaxLength(255);
        });

        modelBuilder.Entity<BomDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("bom_detail", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.FixedScrapQty).HasComment("Số lượng hao hụt cố định");
            entity.Property(e => e.ProductId).HasComment("ID nguyên vật liệu hoặc bán thành phẩm");
            entity.Property(e => e.Quantity).HasPrecision(18, 6);
            entity.Property(e => e.ScrapRate)
                .HasPrecision(8, 4)
                .HasComment("% hao hụt");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Factory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("factory", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.FactoryCode).HasMaxLength(50);
            entity.Property(e => e.FactoryName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Function>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("functions", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.FunctionGroupId, "IX");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.FunctionCode).HasMaxLength(50);
            entity.Property(e => e.FunctionName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<FunctionGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("function_group", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.ParentId, "IX_ParentId");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Holiday>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("holiday", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.HolidayCode).HasMaxLength(50);
            entity.Property(e => e.HolidayName).HasMaxLength(255);
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Line>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("line", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.LayoutImage).HasMaxLength(550);
            entity.Property(e => e.LineCode).HasMaxLength(50);
            entity.Property(e => e.LineName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Machine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("machine", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.MachineCode).HasMaxLength(50);
            entity.Property(e => e.MachineName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<MachineType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("machine_type", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.MachineTypeCode).HasMaxLength(50);
            entity.Property(e => e.MachineTypeName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("menu", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.ParentId, "IX_ParentId");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Icon).HasColumnType("text");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Url).HasMaxLength(255);
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("organization", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.HasIndex(e => e.ParentId, "IX_ParentId");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.OrganizationCode).HasMaxLength(50);
            entity.Property(e => e.OrganizationName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("product", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DrawingNo).HasMaxLength(255);
            entity.Property(e => e.DrawingPath).HasMaxLength(255);
            entity.Property(e => e.ProductCode).HasMaxLength(50);
            entity.Property(e => e.ProductName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("product_type", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.ProductTypeCode).HasMaxLength(50);
            entity.Property(e => e.ProductTypeName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductUnit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("product_unit", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.ConversionFactor).HasPrecision(24, 10);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("shift", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.CrossDay)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.EndTime).HasColumnType("time");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.ShiftCode).HasMaxLength(50);
            entity.Property(e => e.ShiftName).HasMaxLength(255);
            entity.Property(e => e.StartTime).HasColumnType("time");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WorkingMinute).HasPrecision(10, 2);
        });

        modelBuilder.Entity<ShiftBreak>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("shift_break", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.BreakName).HasMaxLength(255);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime).HasColumnType("time");
            entity.Property(e => e.StartTime).HasColumnType("time");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TableBase>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("table_base", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("unit", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DecimalPlaces).HasDefaultValueSql("'2'");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.IsBaseUnit)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.Symbol).HasMaxLength(255);
            entity.Property(e => e.UnitCode).HasMaxLength(50);
            entity.Property(e => e.UnitName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UnitCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("unit_category", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'");
            entity.Property(e => e.UnitCategoryCode).HasMaxLength(50);
            entity.Property(e => e.UnitCategoryName).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UnitConversion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("unit_conversion", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.DivideValue).HasPrecision(24, 10);
            entity.Property(e => e.FormulaType)
                .HasDefaultValueSql("'1'")
                .HasComment("1: MULTIPLY 2: DIVIDE");
            entity.Property(e => e.IsActive).HasDefaultValueSql("'1'");
            entity.Property(e => e.MultiplyValue).HasPrecision(24, 10);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("users", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(550);
            entity.Property(e => e.FullName).HasMaxLength(550);
            entity.Property(e => e.IsAdmin)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.LoginName).HasMaxLength(255);
            entity.Property(e => e.PasswordHash).HasColumnType("text");
            entity.Property(e => e.RefreshToken).HasMaxLength(255);
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_group", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGroupLink>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_group_link", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGroupRightDistribution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_group_right_distribution", tb => tb.HasComment("Base Template Table"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreatedDate, "IX_CreatedDate");

            entity.HasIndex(e => e.IsDeleted, "IX_IsDeleted");

            entity.Property(e => e.Id).HasComment("Primary Key");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}