<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RFactory.Application\RFactory.Application.csproj" />
    <ProjectReference Include="..\RFactory.Infrastructure\RFactory.Infrastructure.csproj" />
    <ProjectReference Include="..\RFactory.Shared\RFactory.Shared.csproj" />
  </ItemGroup>

</Project>
