// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class BomDetail
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public long? BomId { get; set; }

    /// <summary>
    /// ID nguyên vật liệu hoặc bán thành phẩm
    /// </summary>
    public long? ProductId { get; set; }

    public decimal? Quantity { get; set; }

    public long? UnitId { get; set; }

    /// <summary>
    /// % hao hụt
    /// </summary>
    public decimal? ScrapRate { get; set; }

    /// <summary>
    /// Số lượng hao hụt cố định
    /// </summary>
    public int? FixedScrapQty { get; set; }
}