// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class CustomerContact
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// ID khách hàng
    /// </summary>
    public ulong CustomerId { get; set; }

    /// <summary>
    /// Tên người liên hệ
    /// </summary>
    public string ContactName { get; set; }

    /// <summary>
    /// Loại liên hệ: 1=Mua hàng, 2=Kỹ thuật, 3=Chất lượng, 4=Giao nhận, 5=Kế toán, 99=Khác
    /// </summary>
    public int? ContactType { get; set; }

    /// <summary>
    /// Chức vụ
    /// </summary>
    public string Position { get; set; }

    /// <summary>
    /// Số điện thoại
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// Email
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// Liên hệ chính: 1=Có, 0=Không
    /// </summary>
    public bool IsPrimary { get; set; }

    /// <summary>
    /// Trạng thái: 1=Đang hoạt động, 0=Ngừng hoạt động
    /// </summary>
    public bool? IsActive { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }
}