// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class Customer
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã khách hàng
    /// </summary>
    public string CustomerCode { get; set; }

    /// <summary>
    /// Tên khách hàng
    /// </summary>
    public string CustomerName { get; set; }

    /// <summary>
    /// Tên viết tắt
    /// </summary>
    public string ShortName { get; set; }

    /// <summary>
    /// Tên tiếng Anh
    /// </summary>
    public string EnglishName { get; set; }

    /// <summary>
    /// Loại khách hàng: 1=Domestic, 2=International, 3=Internal, 99=Other
    /// </summary>
    public int? CustomerType { get; set; }

    /// <summary>
    /// Mã số thuế
    /// </summary>
    public string TaxCode { get; set; }

    /// <summary>
    /// Người liên hệ chính
    /// </summary>
    public string ContactPerson { get; set; }

    /// <summary>
    /// Số điện thoại
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// Email
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// Địa chỉ
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// Quốc gia
    /// </summary>
    public long? CountryId { get; set; }

    /// <summary>
    /// ID tỉnh/thành phố
    /// </summary>
    public ulong? ProvinceId { get; set; }

    /// <summary>
    /// ID quận/huyện
    /// </summary>
    public ulong? DistrictId { get; set; }

    /// <summary>
    /// Điều khoản thanh toán
    /// </summary>
    public string PaymentTerm { get; set; }

    /// <summary>
    /// ID loại tiền tệ
    /// </summary>
    public ulong? CurrencyId { get; set; }

    /// <summary>
    /// ID kho mặc định
    /// </summary>
    public ulong? DefaultWarehouseId { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }

    /// <summary>
    /// Trạng thái: 1=Đang hoạt động, 0=Ngừng hoạt động
    /// </summary>
    public bool? IsActive { get; set; }
}