// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class Defect
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong DefectGroupId { get; set; }

    public string DefectCode { get; set; }

    public string DefectName { get; set; }

    public string ShortName { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// 1: Minor; 2: Major ; 3: Critical
    /// </summary>
    public int Severity { get; set; }

    public int SortOrder { get; set; }

    public bool? IsActive { get; set; }
}