// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class DeliveryNoteReceiver
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong DeliveryNoteId { get; set; }

    public string ReceiverName { get; set; }

    public string ContactName { get; set; }

    public string Email1 { get; set; }

    public string Email2 { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }
}