// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class DeliveryNoteItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong DeliveryNoteId { get; set; }

    public ulong? GoodsIssueId { get; set; }

    public ulong? GoodsIssueDetailId { get; set; }

    public ulong ProductId { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public ulong? UnitId { get; set; }

    public string UnitName { get; set; }

    public decimal? OrderedQty { get; set; }

    public decimal? DeliveredQty { get; set; }

    public string Remark { get; set; }
}