// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class DeliveryNote
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string DeliveryNo { get; set; }

    public ulong? WarehouseId { get; set; }

    /// <summary>
    /// 1 = Draft; 2 = Confirmed; 3 = Loading; 4 = Loaded; 5 = InTransit; 6 = Delivered; 7 = Cancelled; 8 = Closed
    /// </summary>
    public int Status { get; set; }

    public string VehicleNo { get; set; }

    /// <summary>
    /// 1: Xe tải; 2: Xe van; 3: Đầu kéo
    /// </summary>
    public int? VehicleType { get; set; }

    /// <summary>
    /// 1: Xe tải; 2: Máy bay; 3: Tàu hỏa; 4: Tàu thủy
    /// </summary>
    public int? TransportMethod { get; set; }

    public string DriverName { get; set; }

    public string DriverPhone { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Volume { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public ulong? PickerId { get; set; }

    public string Remark { get; set; }
}