// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class FailureGroup
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã nhóm hỏng hóc
    /// </summary>
    public string GroupCode { get; set; }

    /// <summary>
    /// Tên nhóm hỏng hóc
    /// </summary>
    public string GroupName { get; set; }

    /// <summary>
    /// Tên viết tắt
    /// </summary>
    public string ShortName { get; set; }

    /// <summary>
    /// Mô tả nhóm hỏng hóc
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Thứ tự hiển thị
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Trạng thái: 1-Active, 0-Inactive
    /// </summary>
    public bool? IsActive { get; set; }
}