// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class FailureCode
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã hỏng hóc
    /// </summary>
    public string Code { get; set; }

    /// <summary>
    /// Tên hỏng hóc
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Tên viết tắt
    /// </summary>
    public string ShortName { get; set; }

    /// <summary>
    /// Mô tả hỏng hóc
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Nhóm hỏng hóc
    /// </summary>
    public ulong? FailureGroupId { get; set; }

    /// <summary>
    /// Mức độ nghiêm trọng: 1-Critical, 2-Major, 3-Minor
    /// </summary>
    public int Severity { get; set; }

    /// <summary>
    /// Trạng thái: 1-Active, 0-Inactive
    /// </summary>
    public bool? IsActive { get; set; }
}