// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class GoodsIssue
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string IssueNo { get; set; }

    public int? IssueType { get; set; }

    public long? WarehouseId { get; set; }

    public string ReferenceType { get; set; }

    public long? ReferenceId { get; set; }

    public DateTime? IssueDate { get; set; }

    /// <summary>
    /// 1: Purchase; 2: Production; 3: Return; 4: Transfer In; 5: Adjustment
    /// </summary>
    public int? Status { get; set; }

    public string Remark { get; set; }

    public long? ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public long? PostedBy { get; set; }

    public DateTime? PostedDate { get; set; }
}