// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InspectionResult
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong InspectionExecutionId { get; set; }

    public ulong InspectionItemId { get; set; }

    public int? SampleNo { get; set; }

    public string ActualValue { get; set; }

    public decimal? NumericValue { get; set; }

    public string TextValue { get; set; }

    public bool? BooleanValue { get; set; }

    /// <summary>
    /// 1=Pending, 2=Pass, 3=Fail, 4=NA
    /// </summary>
    public int Result { get; set; }

    public DateTime? InspectionTime { get; set; }

    public ulong? InspectorId { get; set; }

    public string Remark { get; set; }
}