// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InspectionPlan
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string PlanCode { get; set; }

    public string PlanName { get; set; }

    public ulong ProductId { get; set; }

    public ulong RoutingId { get; set; }

    public ulong QualitySpecificationId { get; set; }

    /// <summary>
    /// 1=IQC, 2=IPQC, 3=OQC, 4=FQC
    /// </summary>
    public int InspectionType { get; set; }

    public string Version { get; set; }

    /// <summary>
    /// 1=Draft, 2=PendingApproval, 3=Approved, 4=Active, 5=Inactive, 6=Expired, 7=Cancelled
    /// </summary>
    public int Status { get; set; }

    public DateTime? EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public ulong? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string Remark { get; set; }

    public ulong? SamplingPlanId { get; set; }
}