// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InspectionItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong InspectionPlanId { get; set; }

    public ulong QualitySpecificationItemId { get; set; }

    public int SequenceNo { get; set; }

    public string InspectionMethod { get; set; }

    public decimal? SampleSize { get; set; }

    public string Frequency { get; set; }

    public bool? IsRequired { get; set; }

    public string Remark { get; set; }
}