// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InspectionExecution
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string ExecutionNo { get; set; }

    public ulong? InspectionPlanId { get; set; }

    public ulong? ProductId { get; set; }

    public string LotNo { get; set; }

    public string SerialNo { get; set; }

    /// <summary>
    /// Lệnh sản xuất
    /// </summary>
    public ulong? ProductionOrderId { get; set; }

    public int InspectionType { get; set; }

    /// <summary>
    /// 1=Pending, 2=InProgress, 3=Passed, 4=Failed, 5=PartiallyPassed, 6=Cancelled
    /// </summary>
    public int Status { get; set; }

    public decimal? SampleSize { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public ulong? InspectorId { get; set; }

    public string Remark { get; set; }
}