// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InventoryCycleCount
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public long? WarehouseId { get; set; }

    public long? WarehouseLocationId { get; set; }

    public DateTime? CountDate { get; set; }

    public int? Status { get; set; }

    /// <summary>
    /// Người kiểm kê
    /// </summary>
    public long? UserId { get; set; }
}