// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InventoryTransaction
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string TransactionNo { get; set; }

    public string TransactionType { get; set; }

    public long? ProductId { get; set; }

    public long? WarehouseId { get; set; }

    public long? WarehouseLocationId { get; set; }

    public decimal? Quantity { get; set; }

    public long? UnitId { get; set; }

    /// <summary>
    /// Ví dụ: Purchase, Order
    /// , Production Order,
    ///  Stock Transfer, 
    /// Cycle Count
    /// , Sales Order
    /// </summary>
    public string ReferenceType { get; set; }

    public long? ReferenceId { get; set; }

    public DateTime? TransactionDate { get; set; }
}