// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InventoryCycleCountDetail
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public long? InventoryCycleCountId { get; set; }

    public long? ProductId { get; set; }

    public string LotNo { get; set; }

    public decimal? SystemQuantity { get; set; }

    public decimal? ActualQuantity { get; set; }

    public decimal? DifferenceQuantity { get; set; }
}