// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class InventoryTransaction
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string TransactionNo { get; set; }

    /// <summary>
    /// 1: RECEIPT; 2: ISSUE; 3: TRANSFER; 4: ADJUST; 5: PRODUCTION_IN; 6: PRODUCTION_OUT; 7: SCRAP
    /// </summary>
    public int? TransactionType { get; set; }

    public ulong? ProductId { get; set; }

    public ulong? WarehouseId { get; set; }

    public ulong? WarehouseLocationId { get; set; }

    public decimal? Quantity { get; set; }

    public ulong? UnitId { get; set; }

    /// <summary>
    /// 1: GR; 2: GI; 3: TRANSFER_IN; 4: TRANSFER_OUT; 5: MATERIAL_ISSUE; 6: MATERIAL_RETURN; 7: PRODUCTION_RECEIPT; 8: PRODUCTION_CONSUME; 9: ADJUSTMENT; 10: SCRAP\n
    /// </summary>
    public int ReferenceType { get; set; }

    public ulong? ReferenceId { get; set; }

    public DateTime? TransactionDate { get; set; }
}