// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Giữ hàng cho Work Order hoặc Sales Order.
/// </summary>
public partial class InventoryReservation
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public long? ProductId { get; set; }

    public long? WarehouseId { get; set; }

    public long? InventoryLotId { get; set; }

    public decimal? Quantity { get; set; }

    public string ReferenceType { get; set; }

    public long? ReferenceId { get; set; }

    public string Status { get; set; }
}