// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Lot
/// </summary>
public partial class Lot
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string LotNo { get; set; }

    public ulong ProductId { get; set; }

    public ulong? SupplierId { get; set; }

    public string SupplierLotNo { get; set; }

    public DateOnly? ManufactureDate { get; set; }

    public DateOnly? ExpireDate { get; set; }

    /// <summary>
    /// 1: AVAILABLE;2: HOLD; 3: BLOCKED; 4: CLOSED
    /// </summary>
    public int? Status { get; set; }
}