// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class LotRule
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã quy tắc Lot
    /// </summary>
    public string RuleCode { get; set; }

    /// <summary>
    /// Tên quy tắc Lot
    /// </summary>
    public string RuleName { get; set; }

    /// <summary>
    /// Mẫu sinh mã Lot
    /// </summary>
    public string Template { get; set; }

    /// <summary>
    /// Tiền tố Lot
    /// </summary>
    public string Prefix { get; set; }

    /// <summary>
    /// Định dạng ngày
    /// </summary>
    public string DateFormat { get; set; }

    /// <summary>
    /// Độ dài số thứ tự
    /// </summary>
    public int? SequenceLength { get; set; }

    /// <summary>
    /// Cách reset sequence: 1 Daily; 2 Monthly; 3 Yearly; 4 Never
    /// </summary>
    public int SequenceResetType { get; set; }

    /// <summary>
    /// Trạng thái: 1 Draft; 2 Active; 3 Inactive
    /// </summary>
    public int Status { get; set; }

    public string Description { get; set; }
}