// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class MaintenancePlan
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã kế hoạch bảo trì
    /// </summary>
    public string PlanCode { get; set; }

    /// <summary>
    /// Tên kế hoạch bảo trì
    /// </summary>
    public string PlanName { get; set; }

    /// <summary>
    /// Loại bảo trì
    /// </summary>
    public ulong MaintenanceTypeId { get; set; }

    /// <summary>
    /// Thiết bị
    /// </summary>
    public ulong MachineId { get; set; }

    /// <summary>
    /// Work Center
    /// </summary>
    public ulong? WorkCenterId { get; set; }

    /// <summary>
    /// Checklist sử dụng
    /// </summary>
    public ulong? MaintenanceChecklistId { get; set; }

    /// <summary>
    /// Chu kỳ bảo trì
    /// </summary>
    public decimal Frequency { get; set; }

    /// <summary>
    /// Đơn vị chu kỳ: 1 Day, 2 Week, 3 Month, 4 Year, 5 Hour, 6 ProductionQuantity
    /// </summary>
    public int FrequencyUnit { get; set; }

    /// <summary>
    /// Ngày bắt đầu áp dụng
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Ngày kết thúc áp dụng
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Ngày bảo trì gần nhất
    /// </summary>
    public DateTime? LastMaintenanceDate { get; set; }

    /// <summary>
    /// Ngày bảo trì tiếp theo
    /// </summary>
    public DateTime? NextMaintenanceDate { get; set; }

    /// <summary>
    /// Mức độ ưu tiên: 1:low, 2:normal; 3:high; 4:critical
    /// </summary>
    public int Priority { get; set; }

    /// <summary>
    /// Trạng thái: 1 Draft, 2 Active, 3 Inactive, 4 Expired
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// Bộ phận phụ trách
    /// </summary>
    public ulong? ResponsibleDepartmentId { get; set; }

    /// <summary>
    /// Nhân viên phụ trách
    /// </summary>
    public ulong? ResponsibleEmployeeId { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }
}