// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class MaintenanceChecklist
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã checklist
    /// </summary>
    public string ChecklistCode { get; set; }

    /// <summary>
    /// Tên checklist
    /// </summary>
    public string ChecklistName { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Phiên bản checklist
    /// </summary>
    public int Version { get; set; }

    /// <summary>
    /// Trạng thái: 1 Draft, 2 Active, 3 Inactive
    /// </summary>
    public int Status { get; set; }
}