// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class MaintenanceType
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã loại bảo trì
    /// </summary>
    public string TypeCode { get; set; }

    /// <summary>
    /// Tên loại bảo trì
    /// </summary>
    public string TypeName { get; set; }

    /// <summary>
    /// Tên viết tắt
    /// </summary>
    public string ShortName { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Nhóm loại bảo trì: 1 Planned, 2 Unplanned, 3 Condition, 4 Special
    /// </summary>
    public int? TypeCategory { get; set; }

    /// <summary>
    /// Mức độ ưu tiên mặc định: 1:low, 2:normal; 3:high; 4:critical
    /// </summary>
    public int? Priority { get; set; }

    /// <summary>
    /// Thứ tự hiển thị
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// Trạng thái sử dụng
    /// </summary>
    public bool? IsActive { get; set; }
}