// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class MaintenanceOrder
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã lệnh bảo trì
    /// </summary>
    public string OrderNo { get; set; }

    /// <summary>
    /// Kế hoạch bảo trì
    /// </summary>
    public ulong? MaintenancePlanId { get; set; }

    /// <summary>
    /// Loại bảo trì
    /// </summary>
    public ulong MaintenanceTypeId { get; set; }

    /// <summary>
    /// Thiết bị
    /// </summary>
    public ulong MachineId { get; set; }

    /// <summary>
    /// Mức độ ưu tiên: 1:low, 2:normal; 3:high; 4:critical
    /// </summary>
    public int Priority { get; set; }

    /// <summary>
    /// Trạng thái: 1 Draft, 2 Released, 3 InProgress, 4 Completed, 5 Cancelled
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// Thời gian dự kiến bắt đầu
    /// </summary>
    public DateTime? PlannedStartDate { get; set; }

    /// <summary>
    /// Thời gian dự kiến kết thúc
    /// </summary>
    public DateTime? PlannedEndDate { get; set; }

    /// <summary>
    /// Thời gian thực tế bắt đầu
    /// </summary>
    public DateTime? ActualStartDate { get; set; }

    /// <summary>
    /// Thời gian thực tế kết thúc
    /// </summary>
    public DateTime? ActualEndDate { get; set; }

    /// <summary>
    /// Nhân viên phụ trách
    /// </summary>
    public ulong? ResponsibleEmployeeId { get; set; }

    /// <summary>
    /// Nội dung bảo trì
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Ghi chú hoàn thành
    /// </summary>
    public string CompletionNote { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }
}