// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class MaintenanceOrderChecklist
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Lệnh bảo trì
    /// </summary>
    public ulong MaintenanceOrderId { get; set; }

    /// <summary>
    /// Checklist template
    /// </summary>
    public ulong? MaintenanceChecklistId { get; set; }

    /// <summary>
    /// Mã checklist tại thời điểm thực hiện
    /// </summary>
    public string ChecklistCode { get; set; }

    /// <summary>
    /// Tên checklist tại thời điểm thực hiện
    /// </summary>
    public string ChecklistName { get; set; }

    /// <summary>
    /// Phiên bản checklist
    /// </summary>
    public int? ChecklistVersion { get; set; }

    /// <summary>
    /// Trạng thái: 1 Pending, 2 InProgress, 3 Completed
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// Thời gian bắt đầu
    /// </summary>
    public DateTime? StartedDate { get; set; }

    /// <summary>
    /// Thời gian hoàn thành
    /// </summary>
    public DateTime? CompletedDate { get; set; }

    /// <summary>
    /// Người hoàn thành
    /// </summary>
    public ulong? CompletedBy { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }
}