// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class MaintenanceChecklistItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Checklist
    /// </summary>
    public ulong? MaintenanceChecklistId { get; set; }

    /// <summary>
    /// Thứ tự thực hiện
    /// </summary>
    public int SequenceNo { get; set; }

    /// <summary>
    /// Mã hạng mục
    /// </summary>
    public string ItemCode { get; set; }

    /// <summary>
    /// Tên hạng mục kiểm tra
    /// </summary>
    public string ItemName { get; set; }

    /// <summary>
    /// Loại kiểm tra: 1 YesNo, 2 Numeric, 3 Text, 4 Selection, 5 PassFail, 6 Inspection
    /// </summary>
    public int CheckType { get; set; }

    /// <summary>
    /// Đơn vị đo
    /// </summary>
    public ulong? UnitId { get; set; }

    /// <summary>
    /// Giá trị tiêu chuẩn
    /// </summary>
    public decimal? TargetValue { get; set; }

    /// <summary>
    /// Giá trị tối thiểu
    /// </summary>
    public decimal? MinValue { get; set; }

    /// <summary>
    /// Giá trị tối đa
    /// </summary>
    public decimal? MaxValue { get; set; }

    /// <summary>
    /// Kết quả mong đợi
    /// </summary>
    public string ExpectedResult { get; set; }

    /// <summary>
    /// Bắt buộc thực hiện
    /// </summary>
    public bool? IsRequired { get; set; }

    /// <summary>
    /// Trạng thái sử dụng
    /// </summary>
    public bool? IsActive { get; set; }
}