// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class Menu
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public string Icon { get; set; }

    public int? Order { get; set; }

    public long? ParentId { get; set; }
}