// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PackingScanLog
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong PackingCheckId { get; set; }

    public ulong? PackingCheckItemId { get; set; }

    public ulong? PackingPackageId { get; set; }

    public ulong? ProductId { get; set; }

    public ulong? LotId { get; set; }

    public string SerialNo { get; set; }

    public string Barcode { get; set; }

    public decimal? Quantity { get; set; }

    /// <summary>
    /// 1: Scan; 2: Manual; 3: Remove; 4: Adjust
    /// </summary>
    public int ScanType { get; set; }

    /// <summary>
    /// 1: Success; 2: WrongProduct; 3: Excess; 4: Duplicate; 5: InvalidBarcode; 6: WrongLot; 7: WrongSerial; 8: NotInOrder
    /// </summary>
    public int Result { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime ScannedAt { get; set; }

    public ulong? ScannedBy { get; set; }
}