// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PackingPackageItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong PackingPackageId { get; set; }

    public ulong PackingCheckItemId { get; set; }

    public ulong ProductId { get; set; }

    public ulong? UnitId { get; set; }

    public ulong? LotId { get; set; }

    public string SerialNo { get; set; }

    public decimal? Quantity { get; set; }

    public string Barcode { get; set; }

    public DateTime? ScannedAt { get; set; }

    public ulong? ScannedBy { get; set; }

    public string Remark { get; set; }
}