// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PackingCheck
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string CheckNo { get; set; }

    public ulong? WarehouseId { get; set; }

    public ulong? PickingPlanId { get; set; }

    /// <summary>
    /// 1: Draft; 2 :Checking; 3: Discrepancy; 4: Completed; 5: Cancelled; 6: Closed
    /// </summary>
    public int Status { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public ulong? CheckedBy { get; set; }

    public string Remark { get; set; }
}