// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PackingCheckItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong PackingCheckId { get; set; }

    public ulong ProductId { get; set; }

    public ulong? UnitId { get; set; }

    public ulong? LotId { get; set; }

    public string SerialNo { get; set; }

    public decimal? RequiredQty { get; set; }

    public decimal? PickedQty { get; set; }

    public decimal? PackedQty { get; set; }

    public decimal? RemainingQty { get; set; }

    public decimal? DiscrepancyQty { get; set; }

    /// <summary>
    /// 1: Pending; 2: Checking; 3: Short; 4: Excess; 5: Matched; 6: WrongProduct; 7: Completed
    /// </summary>
    public int Status { get; set; }

    public string Remark { get; set; }
}