// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PackingPackage
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong PackingCheckId { get; set; }

    public string PackageNo { get; set; }

    /// <summary>
    /// 1: Carton; 2: Pallet; 3: Bag; 4: Crate; 5: Other
    /// </summary>
    public int? PackageType { get; set; }

    public string Barcode { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Length { get; set; }

    public decimal? Width { get; set; }

    public decimal? Height { get; set; }

    public decimal? Volume { get; set; }

    /// <summary>
    /// 1: Open; 2: Packing; 3: Packed; 4: Closed; 5: Cancelled
    /// </summary>
    public int Status { get; set; }

    public DateTime? PackedAt { get; set; }

    public ulong? PackedBy { get; set; }

    public string Remark { get; set; }
}