// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PickingTicketItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int? PickingTicketId { get; set; }

    public int? PickingPlanItemId { get; set; }

    public int? ProductId { get; set; }

    public int? LocationId { get; set; }

    public int? LotId { get; set; }

    public string SerialNo { get; set; }

    public decimal? RequestedQty { get; set; }

    public decimal? PickedQty { get; set; }

    /// <summary>
    /// 1:Pending (Chờ lấy), 2:Picking (Đang lấy), 3:PartiallyPicked (Lấy một phần), 4:Picked (Đã lấy đủ), 5:Skipped (Không lấy), 6:Cancelled (Đã hủy)
    /// </summary>
    public int? Status { get; set; }

    public string Remark { get; set; }
}