// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PickingPlanItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int? PickingPlanId { get; set; }

    public int? ProductId { get; set; }

    public int? UnitId { get; set; }

    public decimal? RequiredQty { get; set; }

    public decimal? AllocatedQty { get; set; }

    public decimal? PickedQty { get; set; }

    public decimal? RemainingQty { get; set; }

    /// <summary>
    /// 1:Pending, 2:Picking, 3:PartiallyPicked, 4:FullyPicked, 5:Cancelled
    /// </summary>
    public int? Status { get; set; }

    public string Remark { get; set; }
}