// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class PickingPlanSource
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int? PickingPlanId { get; set; }

    /// <summary>
    /// 1:Goods Issue; 2: Tranfer Request
    /// </summary>
    public int? SourceType { get; set; }

    public int? SourceId { get; set; }

    public string SourceNo { get; set; }
}