// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// 		
/// </summary>
public partial class PickingPlanItemSource
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int? PickingPlanItemId { get; set; }

    public int? SourceId { get; set; }

    public int? SourceDetailId { get; set; }

    public decimal? RequiredQty { get; set; }

    public decimal? PickedQty { get; set; }
}