// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class ProductLotRule
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Sản phẩm
    /// </summary>
    public ulong ProductId { get; set; }

    /// <summary>
    /// Quy tắc Lot
    /// </summary>
    public ulong LotRuleId { get; set; }

    /// <summary>
    /// Có phải quy tắc mặc định hay không
    /// </summary>
    public bool? IsDefault { get; set; }

    /// <summary>
    /// Ngày bắt đầu áp dụng
    /// </summary>
    public DateTime? EffectiveFrom { get; set; }

    /// <summary>
    /// Ngày kết thúc áp dụng
    /// </summary>
    public DateTime? EffectiveTo { get; set; }
}