// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Purchase Order Detail
/// </summary>
public partial class PurchaseOrderDetail
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong PurchaseOrderId { get; set; }

    public ulong ProductId { get; set; }

    public ulong UnitId { get; set; }

    public decimal Quantity { get; set; }

    public decimal? UnitPrice { get; set; }
}