// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Purchase Order Delivery Schedule
/// </summary>
public partial class PurchaseOrderDeliverySchedule
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong PurchaseOrderDetailId { get; set; }

    public DateTime DeliveryDate { get; set; }

    public decimal Quantity { get; set; }
}