// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class QualitySpecificationItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong? QualitySpecificationId { get; set; }

    public int SequenceNo { get; set; }

    public string ParameterCode { get; set; }

    public string ParameterName { get; set; }

    public ulong? UnitId { get; set; }

    public string TargetValue { get; set; }

    public decimal? MinValue { get; set; }

    public decimal? MaxValue { get; set; }

    public bool? IsRequired { get; set; }

    public string Remark { get; set; }
}