// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class QualitySpecification
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string SpecificationCode { get; set; }

    public string SpecificationName { get; set; }

    public string Version { get; set; }

    /// <summary>
    /// 1: IQC (Incoming Quality Control); 2: IPQC (In-Process Quality Control); 3: OQC (Outgoing Quality Control); 4: FQC (Final Quality Control)
    /// </summary>
    public int InspectionType { get; set; }

    /// <summary>
    /// 1: Draft; 2: PendingApproval; 3: Approved; 4: Active; 5: Inactive; 6: Expired; 7: Cancelled
    /// </summary>
    public int Status { get; set; }

    public DateTime? EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public string Remark { get; set; }
}