// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class RoutingOperation
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public long? RoutingId { get; set; }

    public int? Sequence { get; set; }

    public string RoutingOperationCode { get; set; }

    public string RoutingOperationName { get; set; }

    public string Description { get; set; }

    public bool IsFinishOperation { get; set; }

    public bool IsOutputOperation { get; set; }
}