// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class SamplingPlanRule
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public ulong? SamplingPlanId { get; set; }

    public ulong? LotSizeFrom { get; set; }

    public ulong? LotSizeTo { get; set; }

    public ulong? SampleSize { get; set; }

    public int? AcceptanceNumber { get; set; }

    public int? RejectionNumber { get; set; }

    public int SortOrder { get; set; }
}