// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class Serial
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã Serial duy nhất
    /// </summary>
    public string SerialNo { get; set; }

    /// <summary>
    /// Sản phẩm của Serial
    /// </summary>
    public ulong ProductId { get; set; }

    /// <summary>
    /// Lô hàng của Serial
    /// </summary>
    public ulong? LotId { get; set; }

    /// <summary>
    /// Quy tắc Serial đã sử dụng
    /// </summary>
    public ulong? SerialRuleId { get; set; }

    /// <summary>
    /// Sequence record đã cấp số
    /// </summary>
    public ulong? SerialRuleSequenceId { get; set; }

    /// <summary>
    /// Số thứ tự được cấp
    /// </summary>
    public ulong? SequenceNo { get; set; }

    /// <summary>
    /// Trạng thái Serial: 1 Available, 2 Used, 3 Hold, 4 Blocked, 5 Scrapped
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// Ngày sản xuất
    /// </summary>
    public DateTime? ManufactureDate { get; set; }

    /// <summary>
    /// Ngày kích hoạt Serial
    /// </summary>
    public DateTime? ActivatedDate { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }
}