// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class SerialRuleSequence
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// ID quy tắc Serial
    /// </summary>
    public ulong SerialRuleId { get; set; }

    /// <summary>
    /// Kỳ sequence, ví dụ 20261006, 202610, 2026 hoặc GLOBAL
    /// </summary>
    public string SequencePeriod { get; set; }

    /// <summary>
    /// Sequence hiện tại
    /// </summary>
    public ulong CurrentSequence { get; set; }
}