// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class SerialRule
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã quy tắc Serial
    /// </summary>
    public string RuleCode { get; set; }

    /// <summary>
    /// Tên quy tắc Serial
    /// </summary>
    public string RuleName { get; set; }

    /// <summary>
    /// Sản phẩm áp dụng quy tắc
    /// </summary>
    public ulong ProductId { get; set; }

    /// <summary>
    /// Tiền tố Serial
    /// </summary>
    public string Prefix { get; set; }

    /// <summary>
    /// Hậu tố Serial
    /// </summary>
    public string Suffix { get; set; }

    /// <summary>
    /// Định dạng ngày, ví dụ yyyyMMdd
    /// </summary>
    public string DateFormat { get; set; }

    /// <summary>
    /// Ký tự phân cách các thành phần
    /// </summary>
    public string Separator { get; set; }

    /// <summary>
    /// Số chữ số của sequence
    /// </summary>
    public int SequenceLength { get; set; }

    /// <summary>
    /// Kiểu reset: 1 Never, 2 Daily, 3 Monthly, 4 Yearly
    /// </summary>
    public int SequenceResetType { get; set; }

    /// <summary>
    /// Mẫu sinh Serial, ví dụ {PREFIX}{SEP}{DATE}{SEP}{SEQ}
    /// </summary>
    public string Pattern { get; set; }

    /// <summary>
    /// Trạng thái: 1 Active, 2 Inactive
    /// </summary>
    public bool? IsActive { get; set; }

    /// <summary>
    /// Quy tắc mặc định của sản phẩm
    /// </summary>
    public bool IsDefault { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }
}