// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class StockTransfer
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string TransferNo { get; set; }

    public long? FromWarehouseId { get; set; }

    public long? ToWarehouseId { get; set; }

    public DateTime? TransferDate { get; set; }

    /// <summary>
    /// 1: Draft; 2: Approved; 3: Posted; 4: Cancelled
    /// </summary>
    public int Status { get; set; }

    public string Remark { get; set; }

    public long? PostedBy { get; set; }

    public DateTime? PostedDate { get; set; }
}