// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class Supplier
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string SupplierCode { get; set; }

    public string SupplierName { get; set; }

    public string ShortName { get; set; }

    public string TaxCode { get; set; }

    public string SupplierType { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string ContactPerson { get; set; }

    public string PaymentTerm { get; set; }

    public string CurrencyCode { get; set; }

    public int Status { get; set; }

    public string Description { get; set; }
}