// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class TraceabilityType
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Thứ tự hiển thị
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Mã loại truy xuất
    /// </summary>
    public string TraceCode { get; set; }

    /// <summary>
    /// Tên loại truy xuất
    /// </summary>
    public string TraceName { get; set; }

    /// <summary>
    /// Trạng thái sử dụng
    /// </summary>
    public bool? IsActive { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }
}