// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class TraceabilityRecord
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Quy tắc truy xuất
    /// </summary>
    public ulong? TraceabilityRuleId { get; set; }

    /// <summary>
    /// Loại đối tượng truy xuất
    /// </summary>
    public ulong TraceTypeId { get; set; }

    /// <summary>
    /// Id đối tượng
    /// </summary>
    public ulong ObjectId { get; set; }

    public string ObjectNo { get; set; }

    /// <summary>
    /// Loại nghiệp vụ/chứng từ
    /// </summary>
    public string ReferenceType { get; set; }

    /// <summary>
    /// Id nghiệp vụ/chứng từ
    /// </summary>
    public ulong? ReferenceId { get; set; }

    /// <summary>
    /// Thời điểm truy xuất
    /// </summary>
    public DateTime TraceDate { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Remark { get; set; }
}