// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class TraceabilityRuleItem
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Quy tắc truy xuất
    /// </summary>
    public ulong TraceabilityRuleId { get; set; }

    /// <summary>
    /// Loại đối tượng truy xuất
    /// </summary>
    public ulong TraceTypeId { get; set; }

    /// <summary>
    /// Có bắt buộc truy xuất
    /// </summary>
    public bool? IsRequired { get; set; }

    /// <summary>
    /// Thứ tự truy xuất
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }
}