// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class TraceabilityRule
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã quy tắc truy xuất
    /// </summary>
    public string RuleCode { get; set; }

    /// <summary>
    /// Tên quy tắc truy xuất
    /// </summary>
    public string RuleName { get; set; }

    /// <summary>
    /// Sản phẩm áp dụng
    /// </summary>
    public ulong? ProductId { get; set; }

    /// <summary>
    /// Hướng truy xuất: 1 Forward, 2 Backward, 3 Both
    /// </summary>
    public int TraceDirection { get; set; }

    /// <summary>
    /// Trạng thái sử dụng
    /// </summary>
    public bool? IsActive { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }
}