// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class Unit
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public long? UnitCategoryId { get; set; }

    public string UnitCode { get; set; }

    public string UnitName { get; set; }

    public string Symbol { get; set; }

    public int? DecimalPlaces { get; set; }

    public ulong? IsBaseUnit { get; set; }

    public bool? IsActive { get; set; }
}