// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class UnitConversion
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public long? FromUnitId { get; set; }

    public long? ToUnitId { get; set; }

    public decimal? MultiplyValue { get; set; }

    public decimal? DivideValue { get; set; }

    /// <summary>
    /// 1: MULTIPLY 2: DIVIDE
    /// </summary>
    public int FormulaType { get; set; }

    public bool? IsActive { get; set; }
}