// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RFactory.Infrastructure.Entities;

/// <summary>
/// Base Template Table
/// </summary>
public partial class WarehouseLocation
{
    /// <summary>
    /// Primary Key
    /// </summary>
    public ulong Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public long? WarehouseZoneId { get; set; }

    public string WarehouseLocationCode { get; set; }

    public string WarehouseLocationName { get; set; }

    public decimal? MaxCapacity { get; set; }

    public bool? IsPickingLocation { get; set; }

    public bool? IsActive { get; set; }
}